-- BHARAT Study Custom Schema Extensions for OpenSpecimen
-- This file contains the database schema extensions needed for the BHARAT study
-- Author: LIIMS Development Team
-- Date: 2025-07-16

-- 1. Participant grouping and coding table
-- This table maintains the BHARAT-specific participant coding system
CREATE TABLE IF NOT EXISTS os_bharat_participants (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  PARTICIPANT_ID BIGINT NOT NULL,
  CENTER_CODE VARCHAR(10) NOT NULL,
  AGE_GROUP INT NOT NULL CHECK (AGE_GROUP BETWEEN 1 AND 5),
  GENDER CHAR(1) NOT NULL CHECK (GENDER IN ('A', 'B')),
  SEQUENTIAL_NUMBER INT NOT NULL,
  FULL_CODE VARCHAR(20) NOT NULL UNIQUE,
  ENROLLMENT_STATUS VARCHAR(20) DEFAULT 'ENROLLED',
  ENROLLMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CREATED_BY BIGINT,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  LAST_UPDATED_BY BIGINT,
  LAST_UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES CATISSUE_PARTICIPANT(IDENTIFIER),
  FOREIGN KEY (CREATED_BY) REFERENCES CATISSUE_USER(IDENTIFIER),
  FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CATISSUE_USER(IDENTIFIER),
  INDEX idx_full_code (FULL_CODE),
  INDEX idx_center_code (CENTER_CODE),
  INDEX idx_age_group (AGE_GROUP),
  INDEX idx_gender (GENDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2. Data integration tracking table
-- Tracks all external data imports from various sources
CREATE TABLE IF NOT EXISTS os_bharat_data_integrations (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  PARTICIPANT_ID BIGINT NOT NULL,
  EPICOLLECT_UUID VARCHAR(100),
  RAW_DATA JSON,
  IMPORTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  IMPORT_STATUS VARCHAR(20) DEFAULT 'SUCCESS',
  ERROR_MESSAGE TEXT,
  CREATED_BY BIGINT,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES CATISSUE_PARTICIPANT(IDENTIFIER),
  FOREIGN KEY (CREATED_BY) REFERENCES CATISSUE_USER(IDENTIFIER),
  INDEX idx_participant_id (PARTICIPANT_ID),
  INDEX idx_epicollect_uuid (EPICOLLECT_UUID),
  INDEX idx_import_date (IMPORTED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2a. Clinical data table for storing vitals and other clinical information
CREATE TABLE IF NOT EXISTS os_bharat_clinical_data (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  CPR_ID BIGINT NOT NULL,
  FIELD_NAME VARCHAR(100) NOT NULL,
  FIELD_VALUE TEXT,
  RECORDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (CPR_ID) REFERENCES CATISSUE_COLL_PROT_REG(IDENTIFIER),
  INDEX idx_cpr_id (CPR_ID),
  INDEX idx_field_name (FIELD_NAME),
  INDEX idx_recorded_at (RECORDED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 3. Multiomics batch tracking table
-- Manages batches for genomics, proteomics, metabolomics analyses
CREATE TABLE IF NOT EXISTS os_bharat_omics_batches (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  BATCH_NAME VARCHAR(100) NOT NULL UNIQUE,
  BATCH_TYPE VARCHAR(50) NOT NULL,
  OMICS_TYPE VARCHAR(50) NOT NULL,
  PLATE_LAYOUT JSON,
  SAMPLE_COUNT INT DEFAULT 0,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PROCESSED_DATE TIMESTAMP,
  STATUS VARCHAR(20) DEFAULT 'CREATED',
  QC_STATUS VARCHAR(20),
  NOTES TEXT,
  CREATED_BY BIGINT,
  LAST_UPDATED_BY BIGINT,
  LAST_UPDATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (CREATED_BY) REFERENCES CATISSUE_USER(IDENTIFIER),
  FOREIGN KEY (LAST_UPDATED_BY) REFERENCES CATISSUE_USER(IDENTIFIER),
  INDEX idx_batch_name (BATCH_NAME),
  INDEX idx_omics_type (OMICS_TYPE),
  INDEX idx_status (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 4. Sample batch mapping table
-- Links samples to their multiomics batches
CREATE TABLE IF NOT EXISTS os_bharat_sample_batches (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  SPECIMEN_ID BIGINT NOT NULL,
  BATCH_ID BIGINT NOT NULL,
  PLATE_POSITION VARCHAR(10),
  PROCESSING_ORDER INT,
  QC_STATUS VARCHAR(20),
  NOTES TEXT,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (SPECIMEN_ID) REFERENCES CATISSUE_SPECIMEN(IDENTIFIER),
  FOREIGN KEY (BATCH_ID) REFERENCES os_bharat_omics_batches(IDENTIFIER),
  UNIQUE KEY uk_specimen_batch (SPECIMEN_ID, BATCH_ID),
  INDEX idx_batch_id (BATCH_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 5. Enrollment tracking table
-- Tracks enrollment statistics by center, age group, and gender
CREATE TABLE IF NOT EXISTS os_bharat_enrollment_stats (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  CENTER_CODE VARCHAR(10) NOT NULL,
  AGE_GROUP INT NOT NULL,
  GENDER CHAR(1) NOT NULL,
  TARGET_COUNT INT NOT NULL DEFAULT 100,
  CURRENT_COUNT INT NOT NULL DEFAULT 0,
  LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (IDENTIFIER),
  UNIQUE KEY uk_center_age_gender (CENTER_CODE, AGE_GROUP, GENDER)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 6. Lab result mapping table
-- Maps external lab results to participants
CREATE TABLE IF NOT EXISTS os_bharat_lab_results (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  PARTICIPANT_ID BIGINT NOT NULL,
  LAB_NAME VARCHAR(50) NOT NULL,
  TEST_DATE DATE NOT NULL,
  RESULT_TYPE VARCHAR(50),
  RESULT_DATA JSON,
  ABNORMAL_FLAGS JSON,
  PDF_PATH VARCHAR(500),
  IMPORT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES CATISSUE_PARTICIPANT(IDENTIFIER),
  INDEX idx_participant_lab (PARTICIPANT_ID, LAB_NAME),
  INDEX idx_test_date (TEST_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 7. Participant timeline events table
-- Stores all events in a participant's journey
CREATE TABLE IF NOT EXISTS os_bharat_timeline_events (
  IDENTIFIER BIGINT NOT NULL AUTO_INCREMENT,
  PARTICIPANT_ID BIGINT NOT NULL,
  EVENT_TYPE VARCHAR(50) NOT NULL,
  EVENT_DATE TIMESTAMP NOT NULL,
  EVENT_DETAILS JSON,
  SOURCE_SYSTEM VARCHAR(50),
  CREATED_BY BIGINT,
  CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (IDENTIFIER),
  FOREIGN KEY (PARTICIPANT_ID) REFERENCES CATISSUE_PARTICIPANT(IDENTIFIER),
  FOREIGN KEY (CREATED_BY) REFERENCES CATISSUE_USER(IDENTIFIER),
  INDEX idx_participant_events (PARTICIPANT_ID, EVENT_DATE),
  INDEX idx_event_type (EVENT_TYPE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Initialize enrollment targets for centers
-- Assuming 3 centers initially: RAM, VEL, PGI
INSERT INTO os_bharat_enrollment_stats (CENTER_CODE, AGE_GROUP, GENDER, TARGET_COUNT)
VALUES 
  -- RAM Center
  ('RAM', 1, 'A', 167), ('RAM', 1, 'B', 167),
  ('RAM', 2, 'A', 167), ('RAM', 2, 'B', 167),
  ('RAM', 3, 'A', 167), ('RAM', 3, 'B', 167),
  ('RAM', 4, 'A', 167), ('RAM', 4, 'B', 167),
  ('RAM', 5, 'A', 167), ('RAM', 5, 'B', 167),
  -- VEL Center
  ('VEL', 1, 'A', 167), ('VEL', 1, 'B', 167),
  ('VEL', 2, 'A', 167), ('VEL', 2, 'B', 167),
  ('VEL', 3, 'A', 167), ('VEL', 3, 'B', 167),
  ('VEL', 4, 'A', 167), ('VEL', 4, 'B', 167),
  ('VEL', 5, 'A', 167), ('VEL', 5, 'B', 167),
  -- PGI Center
  ('PGI', 1, 'A', 166), ('PGI', 1, 'B', 166),
  ('PGI', 2, 'A', 166), ('PGI', 2, 'B', 166),
  ('PGI', 3, 'A', 166), ('PGI', 3, 'B', 166),
  ('PGI', 4, 'A', 166), ('PGI', 4, 'B', 166),
  ('PGI', 5, 'A', 166), ('PGI', 5, 'B', 166)
ON DUPLICATE KEY UPDATE TARGET_COUNT = VALUES(TARGET_COUNT);

-- Create views for easy querying
CREATE OR REPLACE VIEW v_bharat_enrollment_summary AS
SELECT 
  CENTER_CODE,
  AGE_GROUP,
  SUM(CASE WHEN GENDER = 'A' THEN CURRENT_COUNT ELSE 0 END) as MALE_COUNT,
  SUM(CASE WHEN GENDER = 'B' THEN CURRENT_COUNT ELSE 0 END) as FEMALE_COUNT,
  SUM(CURRENT_COUNT) as TOTAL_COUNT,
  SUM(TARGET_COUNT) as TOTAL_TARGET,
  ROUND(SUM(CURRENT_COUNT) * 100.0 / SUM(TARGET_COUNT), 2) as COMPLETION_PERCENTAGE
FROM os_bharat_enrollment_stats
GROUP BY CENTER_CODE, AGE_GROUP;

CREATE OR REPLACE VIEW v_bharat_participant_details AS
SELECT 
  p.IDENTIFIER as PARTICIPANT_ID,
  bp.FULL_CODE,
  bp.CENTER_CODE,
  bp.AGE_GROUP,
  bp.GENDER,
  bp.ENROLLMENT_DATE,
  p.FIRST_NAME,
  p.LAST_NAME,
  p.BIRTH_DATE,
  p.VITAL_STATUS,
  COUNT(DISTINCT s.IDENTIFIER) as SAMPLE_COUNT
FROM CATISSUE_PARTICIPANT p
JOIN os_bharat_participants bp ON p.IDENTIFIER = bp.PARTICIPANT_ID
LEFT JOIN CATISSUE_SPECIMEN s ON p.IDENTIFIER = s.SPECIMEN_COLLECTION_GROUP_ID
GROUP BY p.IDENTIFIER;